### ISSUE TITLE
missing section list

### ISSUE THREAD

**Issue by zackschuster** [zackschuster/completely-fictional#7]
- [x] `poetry`
- [x] `poetry/:series/:id`
- [x] `poetry/:colossus/:champion`
- [x] `essays`
- [x] `essays/:name`
- [x] `reviews`
- [x] `reviews/:name`
- [x] `trackback`
- [x] `trackback/:chapter`
- [x] `large-round-eyes`
- [x] `extras`
- [ ] `extras/:subroute`
- [ ] `go-away`

**Comment by ledge23** [comment]
addendum: find out how aurelia dynamically loads templates based on url params

**Comment by ledge23** [comment]
switching from aurelia to vue, since it fits my site better (reducing overhead since i don't really need a lot of the functionality that angular or aurelia provides, and i refuse to touch react/(flux || redux)). 

i'm taking the future tack that learning a new framework will involve rebuilding my site in it. it provides me a convenient mental model for a site to reuse between frameworks. plus, my site's fairly simple but is just complex enough that i can dig into how a framework handles things without going too deep into the boonies.
